### ISSUE TITLE
getting Layout Error! Scheme found before folio entry. when i try to clone and run the code

### ISSUE THREAD

**Issue by bharath4793** [codereverser/casparser#20]
Hi

when I try to run the example shown in README.md, getting the below error

raise CASParseError("Layout Error! Scheme found before folio entry.")
casparser.exceptions.CASParseError: Layout Error! Scheme found before folio entry.

not sure if I have missed anything, the statement was downloaded from CAMS on 13/01/2021

**Comment by codereverser** [comment]
If you don't mind, can you please send me a cropped screenshot of just the first scheme entry from the CAS (with all personal data removed) ? something like 

![cas_screenshot](https://user-images.githubusercontent.com/8553055/104442504-2997ed80-55bb-11eb-832c-be807f19a53f.jpg)

**Comment by bharath4793** [comment]
Hi Sandeep Somasekharan,

Please find the attach screenshot

Regards
Bharath B

**Comment by codereverser** [comment]
looks like you missed to attach the file

**Comment by bharath4793** [comment]
I have attached the file, still, I have attached once again.
[image: Screen Shot 2021-01-13 at 4.24.07 PM.png]

**Comment by bharath4793** [comment]
do let me know once the issue is resolved

Regards
Bharath B

**Comment by codereverser** [comment]
The image is still not visible here. Looks like github doesn't support attaching images in "Reply via email" . 

Can you please email me the file if you are having issues uploading it here? My email is available in my profile. [codereverser .at. gmail .dot. com]

**Comment by bharath4793** [comment]
I have mailed you and attaching the snapshot here

<img width="973" alt="Screen Shot 2021-01-13 at 4 24 07 PM" src="https://user-images.githubusercontent.com/5348673/104449846-3c172480-55c5-11eb-8451-fc4e4cedfad4.png">

**Comment by codereverser** [comment]
Many thanks! 
I've pushed a commit that should resolve this issue. Can you please update your code and test?

**Comment by bharath4793** [comment]
any idea on how to reimport the changes you have done because when I uninstall the requirements and reinstall it using pip, I think it's reinstalling from the cache.

**Comment by bharath4793** [comment]
the previous error seems to be resolved, but getting below error

    raise CASParseError("Unable to parse investor data")
casparser.exceptions.CASParseError: Unable to parse investor data

**Comment by codereverser** [comment]
I've pushed a new version to sort the issues . Try installing it by

```
pip install -U 'casparser[mupdf]==0.4.1'
```

If the error still persists, please give `force_pdfminer` option a try and let me know 

via API, 
```python
data = read_cas_pdf(filename, password, force_pdfminer=True)
```
or via CLI, 
```
casparser -p password --force-pdfminer filename
```

**Comment by bharath4793** [comment]
even after adding the above parameter the error still persists

`Traceback (most recent call last):
  File "<project dir>/parse_mf_cams_pdf.py", line 113, in <module>
    csv_json()
  File "<project dir>/parse_mf_cams_pdf.py", line 96, in csv_json
    data = casparser.read_cas_pdf(pdf_path, "password", force_pdfminer=True)
  File "<project dir>/venv/lib/python3.8/site-packages/casparser/parsers/__init__.py", line 25, in read_cas_pdf
    partial_cas_data = cas_pdf_to_text(filename, password)
  File "<project dir>/venv/lib/python3.8/site-packages/casparser/parsers/pdfminer.py", line 150, in cas_pdf_to_text
    investor_info = parse_investor_info(layout, *page.mediabox[2:])
  File "<project dir>/venv/lib/python3.8/site-packages/casparser/parsers/pdfminer.py", line 53, in parse_investor_info
    raise CASParseError("Unable to parse investor data")
casparser.exceptions.CASParseError: Unable to parse investor data`

with Cli getting below error
Error parsing pdf file:: Unable to parse investor data

**Comment by codereverser** [comment]
fixed in https://github.com/codereverser/casparser/commit/76cf58265deb4142c7db3c6cc0b3b66d12461a41

**Comment by developerdiary** [comment]
I installed the latest package still getting same issue  "Unable to parse investor data"

**Comment by codereverser** [comment]
In that case, it would be difficult to fix this without looking at the actual CAS file (or at least the layout of investor info). It is working for all the sample files I have. May be the contact details are in a different format than the ones I've seen. 

Can you please send me the casparser version? 
```
casparser --version
```

**Comment by developerdiary** [comment]
Version : 0.7.4
I can share with you my CAS file. Please share your email address

**Comment by codereverser** [comment]
CAS file would be super helpful. many thanks! may be it is some regression bug in one of the new releases.  

my email id is there in the profile https://github.com/codereverser
